version: "3.8"
services:
  rpi-shiny-server:
    image: shiny-server-arm:latest
    container_name: rpi-shiny-server-docker
    ports:
      - 3838:3838
    volumes:
       - shiny-apps:/srv/shiny-server/
       - shiny-logs:/var/log/shiny-server/
       - shiny-conf:/etc/shiny-server/
    restart: always

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-dumps:/etc/db-dumps
      - ./db-data/:/var/lib/postgresql/data/
    restart: always

volumes:
  shiny-apps:
    name: shiny-apps
    driver_opts:
      type: none
      device: ~/shiny-server/apps/
      o: bind
  shiny-logs:
    name: shiny-logs
    driver_opts:
      type: none
      device: ~/shiny-server/logs/
      o: bind
  shiny-conf:
    name: shiny-conf
    driver_opts:
      type: none
      device: ~/shiny-server/conf/
      o: bind
  db-dumps:
    name: db-dumps
    driver_opts:
      type: none
      device: ~/shiny-server/db-dumps
      o: bind
